In [2]:
import numpy as np

a = np.array([1,2.1,2,3,1,2,3,1,2,3,4,20])

In [19]:
a_count = np.bincount(a)
display(a_count)

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [17]:
np.argmax(a_count)

2

In [51]:
x = np.arange(6).reshape(-1,2)
y = np.arange(4,12).reshape(2,2,2)
x, y


(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11]]]))

In [7]:
np.square(x), np.square(y).transpose()

(array([[ 0,  1],
        [ 4,  9],
        [16, 25]], dtype=int32),
 array([[ 16,  36,  64, 100],
        [ 25,  49,  81, 121]], dtype=int32))

In [17]:
np.sum(np.square(x), axis=1, keepdims=True) , np.sum(np.square(y), axis=1, keepdims=True).transpose()
np.sum(np.square(x), axis=1, keepdims=True) + np.sum(np.square(y), axis=1, keepdims=True).transpose()

array([[ 42,  86, 146, 222],
       [ 54,  98, 158, 234],
       [ 82, 126, 186, 262]], dtype=int32)

In [19]:
np.sqrt(
    np.sum(np.square(x), axis=1, keepdims=True)
    + np.sum(np.square(y), axis=1, keepdims=True).transpose()
    - 2*np.dot(x, y.transpose())
)

array([[ 5.65685425,  8.48528137, 11.3137085 , 14.14213562],
       [ 2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [ 0.        ,  2.82842712,  5.65685425,  8.48528137]])

In [20]:
np.sqrt(np.sum(np.square((x[:, np.newaxis] - y[np.newaxis, :])), axis=2))

array([[ 5.65685425,  8.48528137, 11.3137085 , 14.14213562],
       [ 2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [ 0.        ,  2.82842712,  5.65685425,  8.48528137]])

In [29]:

y.shape, type(y) == np.ndarray
# y.reshape((y.shape[1] = 0))

((2, 2, 2), True)

In [40]:
def collapse(array: np.ndarray) -> np.ndarray:
    shape = np.array(array.shape)
    new_shape = np.insert(shape[2:], 0, shape[0]*shape[1])

    return array.reshape(tuple(new_shape))

In [42]:
collapse(y)

array([[ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [60]:
np.append(x[0:2], x[3:3])

array([0, 1, 2, 3])